apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-171077183
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-171077183
    app.kubernetes.io/part-of: test-app-171077183
  name: java-quarkus-171077183
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-171077183
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-171077183
    spec:
      containers:
      - image: quay.io/hacdev/debb6fax-tenant/test-app-171077183/java-quarkus-171077183@sha256:b2d3d1dad7986e933f9bde159f025750cbfaddc6accb51f6eb28bb61a92fd3ec
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
